"use client";

import { useState } from "react";
import api from "@/lib/api";
import { describeApiError } from "@/lib/apiErrors";
import { useDashboardGuard } from "@/lib/authGuard";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

export default function AttendancePage() {
  const allowed = useDashboardGuard("student");
  const [token, setToken] = useState("");
  const [message, setMessage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  const markAttendance = async () => {
    setError(null);
    setMessage(null);
    try {
      await api.post("/student/attendance/scan", { token });
      setMessage("Attendance marked successfully.");
      setToken("");
    } catch (e) {
      setError(describeApiError(e));
    }
  };

  if (!allowed) {
    return (
      <main className="p-6">
        <div className="nc-skeleton h-10 w-40 rounded-[8px]" />
      </main>
    );
  }

  return (
    <main className="mx-auto max-w-3xl space-y-4 p-6">
      <h1 className="font-[family-name:var(--font-fraunces)] text-2xl text-[var(--text-primary)]">Attendance scan</h1>
      <Card className="space-y-3 p-4">
        <p className="text-sm text-[var(--text-muted)]">Paste QR token generated by your teacher (valid for 5 minutes).</p>
        <div className="space-y-1.5">
          <Label htmlFor="attendanceToken">Attendance token</Label>
          <Input id="attendanceToken" className="font-mono text-sm" value={token} onChange={(e) => setToken(e.target.value)} />
        </div>
        <Button onClick={markAttendance} disabled={!token.trim()}>
          Mark attendance
        </Button>
      </Card>
      {message && <p className="text-sm text-[var(--accent-success)]">{message}</p>}
      {error && <p className="text-sm text-[var(--accent-danger)]">{error}</p>}
    </main>
  );
}
